networks:
  net:
    driver: bridge

services:
  server:
    container_name: flask_server
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server/server-data:/app/data
    networks:
      - net
    tty: true

  sqlitebrowser:
    image: linuxserver/sqlitebrowser:3.13.1
    container_name: sqlite_browser
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Rome
    volumes:
      - ./server/server-data:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - server

  alice:
    container_name: container_alice
    build:
      context: ./client
      dockerfile: Dockerfile
      target: alice
    command: tail -f /dev/null
    volumes:
      - ./client/alice_keys:/app/my_keys
    networks:
      - net
    depends_on:
      - server
    stdin_open: true
    tty: true

  bob:
    container_name: container_bob
    build:
      context: ./client
      dockerfile: Dockerfile
      target: bob
    command: tail -f /dev/null
    volumes:
      - ./client/bob_keys:/app/my_keys
    networks:
      - net
    depends_on:
      - server
    stdin_open: true
    tty: true